export type Card = {
  name: string;
  number: string;
  arcana: string;
  suit: string;
  img: string;
  fortune_telling: string[];
  keywords: string[];
};

export const tarotCards: Card[] = [
  {
    name: "Le Fou",
    number: "0",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m00.jpg",
    fortune_telling: [
      "Watch for new projects and new beginnings",
      "Prepare to take something on faith",
      "Something new comes your way; go for it",
    ],
    keywords: ["liberté", "foi", "inexpérience", "innocence"],
  },
  {
    name: "Le Bateleur",
    number: "1",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m01.jpg",
    fortune_telling: [
      "A powerful man may play a role in your day",
      "Your current situation must be seen as one element of a much larger plan",
    ],
    keywords: ["capacité", "empowerment", "activité"],
  },
  {
    name: "La Grande Prêtresse",
    number: "2",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m02.jpg",
    fortune_telling: [
      "A mysterious woman arrives",
      "A sexual secret may surfAs",
      "Someone knows more than he or she will reveal",
    ],
    keywords: ["intuition", "réflexion", "pureté", "initiation"],
  },
  {
    name: "L'Impératrice",
    number: "3",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m03.jpg",
    fortune_telling: [
      "Pregnancy is in the cards",
      "An opportunity to be involved in luxurious sexuality is coming",
      "Beware a tendency toward addiction",
    ],
    keywords: ["fertilité", "productivité", "maturité", "nourrissement"],
  },
  {
    name: "L'Empereur",
    number: "4",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m04.jpg",
    fortune_telling: [
      "A father figure arrives",
      "A new employer or authority figure will give you orders",
      "Expect discipline or correction in the near future",
    ],
    keywords: ["autorité", "régulation", "direction", "structure"],
  },
  {
    name: "Le Pape",
    number: "5",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m05.jpg",
    fortune_telling: [
      "Expect to be caught in a misdeed and punished accordingly",
      "Pray for forgiveness and confess wrongdoings",
      "A more experienced man, spiritual leader, or father figure will come into your life",
    ],
    keywords: ["conseils", "connaissances", "révélation", "croyances"],
  },
  {
    name: "L'Amoureux",
    number: "6",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m06.jpg",
    fortune_telling: [
      "A new personal or professional relationship blossoms",
      "Sexual opportunities abound",
      "Unexpectedly, a friend becomes a lover",
    ],
    keywords: ["amour", "passion", "unité", "choix"],
  },
  {
    name: "Le Chariot",
    number: "7",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m07.jpg",
    fortune_telling: [
      "Victory is a certainty",
      "Move ahead with all plans",
      "Beware the jealousy of others",
    ],
    keywords: ["avancement", "victoire", "triomphe", "succès"],
  },
  {
    name: "La Force",
    number: "8",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m08.jpg",
    fortune_telling: [
      "Your self-control will be tested",
      "A woman will seek to change her partner or lover",
      "You are a strong, capable person",
    ],
    keywords: ["discipline", "audace", "autodiscipline", "pouvoir", "vitalité"],
  },
  {
    name: "L'Ermite",
    number: "9",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m09.jpg",
    fortune_telling: [
      "A period of loneliness begins",
      "One partner in a relationship departs",
      "A search for love or money proves fruitless",
    ],
    keywords: ["solitude", "expérience", "calme", "repli"],
  },
  {
    name: "La Route de la Fortune",
    number: "10",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m10.jpg",
    fortune_telling: [
      "Some events are in the hands of heaven",
      "You've lived through this before",
      "What happened then?",
    ],
    keywords: ["chance", "hasard", "cycles", "karma", "destin", "révolution"],
  },
  {
    name: "La Justice",
    number: "11",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m11.jpg",
    fortune_telling: [
      "A legal verdict will be rendered soon",
      "Someone is making a décision",
      "You need to get the facts",
    ],
    keywords: ["équilibre", "loi", "justice", "objectivité"],
  },
  {
    name: "L'Homme Pendu",
    number: "12",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m12.jpg",
    fortune_telling: [
      "A traitor is revealed",
      "One of your friends is working against you",
      "Change your ways or suffer the consequences",
    ],
    keywords: [
      "illumination",
      "sacrifice",
      "perspective",
      "suspension",
      "renversements",
    ],
  },
  {
    name: "La Mort",
    number: "13",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m13.jpg",
    fortune_telling: [
      "A relationship or illness ends suddenly",
      "Limit travel and risk-taking",
      "General gloom and doom",
    ],
    keywords: ["fin", "conclusion", "transition", "passage", "départ"],
  },
  {
    name: "La Tempérance",
    number: "14",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m14.jpg",
    fortune_telling: [
      "Someone's using drugs or alcohol to excess",
      "It's time to get back on that diet",
    ],
    keywords: ["mélange", "synthèse", "médiation", "combinaison", "harmonie"],
  },
  {
    name: "Le Diable",
    number: "15",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m15.jpg",
    fortune_telling: [
      "Adultery and unfaithfulness",
      "A string of extremely bad luck is coming your way",
      "Beware evil influences and wolves in sheep's clothing",
    ],
    keywords: ["ombre", "matérialisme", "captivité", "illusion"],
  },
  {
    name: "La Tour",
    number: "16",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m16.jpg",
    fortune_telling: [
      "Impending disaster",
      "Cancel plans and reverse décisions",
      "Someone wants to take you down a notch or two",
      "Don't hold back; say what you really mean",
    ],
    keywords: [
      "démolition",
      "bouleversement",
      "déconstruction",
      "désastre",
      "déstruction",
    ],
  },
  {
    name: "L'Etoile",
    number: "17",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m17.jpg",
    fortune_telling: [
      "Get an astrology chart drawn up",
      "Someone is a little too starstruck",
      "What's happening now has long been fore-ordained",
    ],
    keywords: [
      "espoir",
      "optimisme",
      "ouverture",
      "certitude",
      "foi",
      "envie",
      "vérité",
    ],
  },
  {
    name: "La Lune",
    number: "18",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m18.jpg",
    fortune_telling: [
      "Watch for problems at the end of the month",
      "Someone you know needs to howl at the moon more often",
      "Someone is about to change his or her mind about an important décision",
    ],
    keywords: ["mystery", "fantasy", "imagination", "rêves", "incertitude"],
  },
  {
    name: "Le Soleil",
    number: "19",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m19.jpg",
    fortune_telling: [
      "Everything's coming up roses (or sunflowers, whatever the case may be)",
      "Whatever's on your mind, go for it because you can't lose today",
    ],
    keywords: ["joie", "éclat", "validation", "attention", "énergie"],
  },
  {
    name: "Le Jugement",
    number: "20",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m20.jpg",
    fortune_telling: [
      "An old issue you thought was over will come up again today",
      "Get ready for huge changes: break-ups, sudden calls from old friends, and unexpected setbacks",
      "God's trying to get your attention",
    ],
    keywords: [
      "réveil",
      "renouveau",
      "résurrection",
      "évaluation",
      "invitation",
    ],
  },
  {
    name: "Le Monde",
    number: "21",
    arcana: "Major Arcana",
    suit: "Trump",
    img: "m21.jpg",
    fortune_telling: [
      "Winning the lottery",
      "Getting your heart's désir",
      "Having everything you ever imagined having",
    ],
    keywords: [
      "intégrité",
      "intégration",
      "totalité",
      "complétude",
      "plénitude",
    ],
  },
  //
  //
  {
    name: "As de Coupe",
    number: "1",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c01.jpg",
    fortune_telling: [
      "Romance is in the cards",
      "A new relationship or marriage is just around the corner",
      "Prayers are answered",
    ],
    keywords: ["intuition", "spiritualité", "affection", "motivation"],
  },
  {
    name: "Deux de Coupe",
    number: "2",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c02.jpg",
    fortune_telling: [
      "Someone has a secret crush on you",
      "Relationships should be mutual; get rid of a leech",
    ],
    keywords: ["union", "attraction", "combinaison", "affection"],
  },
  {
    name: "Trois de Coupe",
    number: "3",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c03.jpg",
    fortune_telling: [
      "Unconventional romance is coming your way: a love affair with someone you've always dismissed",
    ],
    keywords: ["célébration", "expression", "communauté", "convivialité"],
  },
  {
    name: "Quatre de Coupe",
    number: "4",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c04.jpg",
    fortune_telling: [
      "A lover is getting restless",
      "Find out what he or she needs, or new opportunities may lure your partner away",
    ],
    keywords: ["ennui", "apathie", "léthargie", "stabilité", "ingratitude"],
  },
  {
    name: "Cinq de Coupe",
    number: "5",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c05.jpg",
    fortune_telling: [
      "A breakup looms",
      "Don't cry over spilt milk",
      "Take your lumps and get back in the saddle",
    ],
    keywords: [
      "perte",
      "désespoir",
      "réévaluation",
      "regret",
      "incertitude",
      "repentance",
    ],
  },
  {
    name: "Six de Coupe",
    number: "6",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c06.jpg",
    fortune_telling: [
      "A stingy spirit is strangling your enjoyment of life",
      "Loosen up and think of others for once, why don't you?",
    ],
    keywords: ["charité", "partage", "sacrifice", "coopération", "justice"],
  },
  {
    name: "Sept de Coupe",
    number: "7",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c07.jpg",
    fortune_telling: [
      "You're being fed a line",
      "Rather than be dazzled by fancy words and promises, demand something real",
    ],
    keywords: ["imagination", "rêves", "illusions", "objectifs"],
  },
  {
    name: "Huit de Coupe",
    number: "8",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c08.jpg",
    fortune_telling: [
      'Someone\'s "stepping out" on you, now or in the near future',
      "Maybe it's time to quit talking about the problem and just move on",
    ],
    keywords: ["envie", "insatisfaction", "quête", "départ", "repli"],
  },
  {
    name: "Neuf de Coupe",
    number: "9",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c09.jpg",
    fortune_telling: ["Whatever you want, you'll get it"],
    keywords: ["satisfaction", "sensualité", "luxe", "plaisir"],
  },
  {
    name: "Dix de Coupe",
    number: "10",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c10.jpg",
    fortune_telling: [
      "Marriage and family are in the cards",
      "Expect a friendship to blossom into a romance",
    ],
    keywords: ["joie", "accomplissement", "émotion écrasante", "étourderie"],
  },
  {
    name: "Valet de Coupe",
    number: "11",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c11.jpg",
    fortune_telling: [
      "This card represents a young man or woman with a watery, dreamy demeanor, likely born a Libra, Scorpio, or Sagittarius, who wants to start a new relationship with you",
    ],
    keywords: [
      "enthousiasme",
      "premières impressions",
      "romantisme",
      "superficialité",
    ],
  },
  {
    name: "Chevalier de Coupe",
    number: "12",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c12.jpg",
    fortune_telling: [
      "This card represents a man with an emotional, sensitive personality, likely born between October 13th and November 11th, who wants you to rally around his latest passionate cause",
    ],
    keywords: ["ferveur", "zèle", "humeur maussade", "illumination"],
  },
  {
    name: "Reine de Coupe",
    number: "13",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c13.jpg",
    fortune_telling: [
      "This card represents a woman with an emotional, deeply spiritual nature, likely born between June 11th and July 11th, who uses emotional and spiritual appeals to sway others to her point of view",
    ],
    keywords: [
      "perspicacité",
      "spiritualité",
      "compassion",
      "empathie",
      "instinct",
    ],
  },
  {
    name: "Roi de Coupe",
    number: "14",
    arcana: "Minor Arcana",
    suit: "Coupes",
    img: "c14.jpg",
    fortune_telling: [
      "This card represents an older man with a gentle, sensitive presence, likely born between February 9th and March 10th, who is known for his fairness and tolerance",
    ],
    keywords: ["sagesse", "diplomacie", "retenue", "calme"],
  },
  {
    name: "As d'Epée",
    number: "1",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s01.jpg",
    fortune_telling: [
      "The time to make a choice is now",
      "Stop wavering and do what you know is best",
    ],
    keywords: ["logique", "objectivité", "intellecte", "choix"],
  },
  {
    name: "Deux d'Epée",
    number: "2",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s02.jpg",
    fortune_telling: [
      "Sometimes, the only way to win is to refuse to fight",
      "You're stuck for now; let time pass before taking action",
    ],
    keywords: ["refus", "débat", "impasse", "trêve"],
  },
  {
    name: "Trois d'Epée",
    number: "3",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s03.jpg",
    fortune_telling: [
      "Breakups and infidelity abound",
      "What hurts now, though, will turn out to be good for you later on",
    ],
    keywords: ["désaccord", "différence", "insatisfaction", "chagrin", "rejet"],
  },
  {
    name: "Quatre d'Epée",
    number: "4",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s04.jpg",
    fortune_telling: [
      "Don't make any décision now",
      "Wait, and you'll be glad you did",
    ],
    keywords: ["méditation", "contemplation", "perspective", "état d'esprit"],
  },
  {
    name: "Cinq d'Epée",
    number: "5",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s05.jpg",
    fortune_telling: [
      "Someone is stealing from you, financially or romantically",
      "Be wary of friends who talk behind your back",
    ],
    keywords: ["égoïsme", "hostilité", "irrationalité", "auto-préservation"],
  },
  {
    name: "Six d'Epée",
    number: "6",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s06.jpg",
    fortune_telling: [
      "You'll soon go on a long journey over water",
      "Actions have unexpected consequences, so be prepared",
    ],
    keywords: ["adaptation", "ajustements", "science", "voyage"],
  },
  {
    name: "Sept d'Epée",
    number: "7",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s07.jpg",
    fortune_telling: [
      "Don't assume people around you are worthy of your trust",
      "Ask for an accounting of where people have been, and what they've been doing",
    ],
    keywords: ["malhonnêteté", "présomption", "sournoiserie", "hypothèses"],
  },
  {
    name: "Huit d'Epée",
    number: "8",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s08.jpg",
    fortune_telling: [
      "Get over playing the victim",
      "Once you realize you are your own biggest obstacle, nothing can hold you back",
    ],
    keywords: ["restriction", "limitation", "confinement", "impuissance"],
  },
  {
    name: "Neuf d'Epée",
    number: "9",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s09.jpg",
    fortune_telling: [
      "If you take the action you're considering now, you'll be sorry in the future",
    ],
    keywords: ["remords", "inquiétude", "éperdu", "conclusion"],
  },
  {
    name: "Dix d'Epée",
    number: "10",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s10.jpg",
    fortune_telling: [
      "Disaster",
      "Put off plans and do not take action until omens are better",
    ],
    keywords: ["épuisement", "ruine", "désastre", "stamina", "obsession"],
  },
  {
    name: "Valet d'Epée",
    number: "11",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s11.jpg",
    fortune_telling: [
      "This card represents a young man or woman with an airy, intellectual demeanor, likely born a Capricorn, Aquarius, or Pisces, who wants to learn something new from you or have a discussion with you",
    ],
    keywords: ["étudiant", "apprenti", "savoir", "information"],
  },
  {
    name: "Chevalier d'Epée",
    number: "12",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s12.jpg",
    fortune_telling: [
      "A blunder leads someone to say something he or she regrets",
      "If this was you, be prepared to apologize and move on",
    ],
    keywords: ["franchise", "intelligence", "incisivité", "enquête"],
  },
  {
    name: "Reine d'Epée",
    number: "13",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s13.jpg",
    fortune_telling: [
      "This card represents a woman with an artistic, intellectual nature, likely born between September 12th and October 12th, who uses clever, positive communication to sway others to her point of view",
    ],
    keywords: ["compétence", "esprit", "charme", "aptitude"],
  },
  {
    name: "Roi d'Epée",
    number: "14",
    arcana: "Minor Arcana",
    suit: "Epées",
    img: "s14.jpg",
    fortune_telling: [
      "This card represents an older man with an insightful, deliberate spirit, likely born between May 11th and June 10th, who is known for his integrity and sharp décision-making ability",
    ],
    keywords: ["génie", "expertise", "décision", "verdict"],
  },
  {
    name: "As de Bâton",
    number: "1",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w01.jpg",
    fortune_telling: [
      'Someone has the "hots" for you',
      "A new job offer is coming your way",
      "Walk softly, and carry a big stick",
    ],
    keywords: ["désir", "inspiration", "vision", "création", "invention"],
  },
  {
    name: "Deux de Bâton",
    number: "2",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w02.jpg",
    fortune_telling: [
      "Beware false friends",
      "Don't be mealy-mouthed; say what you think and do what you want to do",
    ],
    keywords: ["conflit", "décision", "option", "individualité"],
  },
  {
    name: "Trois de Bâton",
    number: "3",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w03.jpg",
    fortune_telling: [
      "You'll be planning a trip soon",
      "Be on the lookout: your ship is coming in",
    ],
    keywords: ["implémentation", "action", "exploration"],
  },
  {
    name: "Quatre de Bâton",
    number: "4",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w04.jpg",
    fortune_telling: [
      "Someone is watching and evaluating your work",
      "You may get a wedding invitation soon",
    ],
    keywords: [
      "célébration",
      "jubilation",
      "communauté",
      "travail d'équipe",
      "achèvement",
    ],
  },
  {
    name: "Cinq de Bâton",
    number: "5",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w05.jpg",
    fortune_telling: [
      "Prepare for a fight with your best friend",
      "Remember: once you let words loose, you can't take them back",
    ],
    keywords: [
      "confrontation",
      "disruption",
      "distinction",
      "objection",
      "conflit",
    ],
  },
  {
    name: "Six de Bâton",
    number: "6",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w06.jpg",
    fortune_telling: [
      "Someone is planning a party for you, but not everyone feels so good about your recent success",
      "Watch out for envious friends",
    ],
    keywords: ["victoire", "réussite", "succès", "triomphe"],
  },
  {
    name: "Sept de Bâton",
    number: "7",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w07.jpg",
    fortune_telling: [
      "Don't be surprised by a personal attack",
      "Prepare to defend yourself or someone you love",
    ],
    keywords: ["bravoure", "résolution", "détermination"],
  },
  {
    name: "Huit de Bâton",
    number: "8",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w08.jpg",
    fortune_telling: [
      "Watch for a surprising letter in the mail",
      "Your whole world is about to be turned on its ear",
    ],
    keywords: ["vitesse", "agilité", "réactivité", "changement"],
  },
  {
    name: "Neuf de Bâton",
    number: "9",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w09.jpg",
    fortune_telling: [
      "Don't relax yet; there's more to come",
      "The test you're facing now is happening for one reason: to show you who your real friends are",
    ],
    keywords: ["dureté", "persistance", "stamina", "loyauté", "libération"],
  },
  {
    name: "Dix de Bâton",
    number: "10",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w10.jpg",
    fortune_telling: [
      "You're worn out",
      "Back off, take a time out, and let someone else handle things for a while",
    ],
    keywords: ["épuisement", "résistance", "fardeau", "oppression"],
  },
  {
    name: "Valet de Bâton",
    number: "11",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w11.jpg",
    fortune_telling: [
      "This card represents a young man or woman with a fiery, enthusiastic demeanor, likely born a Cancer, Leo, or Virgo, who wants to start a new relationship with you",
    ],
    keywords: [
      "enthousiasme",
      "ardeur",
      "confiance",
      "validation",
      "affirmation",
    ],
  },
  {
    name: "Chevalier de Bâton",
    number: "12",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w12.jpg",
    fortune_telling: [
      "This card represents a man with a bold, passionate personality, likely born between July 12th and August 11th, who wants to sweep you off your feet",
    ],
    keywords: ["audace", "bravado", "passion", "persuasion", "plaidoyer"],
  },
  {
    name: "Reine de Bâton",
    number: "13",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w13.jpg",
    fortune_telling: [
      "This card represents a woman with an attractive, appealing personality, likely born between March 11th and April 20th, who wants to charme you into doing things her way",
    ],
    keywords: ["attention", "attraction", "unification", "collaboration"],
  },
  {
    name: "Roi de Bâton",
    number: "14",
    arcana: "Minor Arcana",
    suit: "Bâtons",
    img: "w14.jpg",
    fortune_telling: [
      "This card represents an older man with a commanding, charismatic personality, likely born between November 13th and December 12th, who prefers to give directions and have them followed",
    ],
    keywords: ["creativité", "ingéniosité", "réussite", "direction"],
  },
  {
    name: "As de Denier",
    number: "1",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p01.jpg",
    fortune_telling: [
      "Your health will improve",
      "The check you're looking for really is in the mail",
    ],
    keywords: ["santé", "richesse", "praticité", "recevoir"],
  },
  {
    name: "Deux de Denier",
    number: "2",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p02.jpg",
    fortune_telling: [
      "It's time to balance the budget",
      "Avoid the temptation to spend critical funds on frivolous goods",
    ],
    keywords: ["évaluation", "décision", "budgétisation", "diagnostic"],
  },
  {
    name: "Trois de Denier",
    number: "3",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p03.jpg",
    fortune_telling: [
      "A high-dollar contract is in your future",
      "If you work hard, you'll succeed",
    ],
    keywords: ["expression", "production", "travail", "contribution"],
  },
  {
    name: "Quatre de Denier",
    number: "4",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p04.jpg",
    fortune_telling: ["A rainy day is coming\u2014it's time to save"],
    keywords: ["protection", "conservation", "préservation", "sécurit"],
  },
  {
    name: "Cinq de Denier",
    number: "5",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p05.jpg",
    fortune_telling: ["Finances are getting tighter", "Prepare for a setback"],
    keywords: ["pauvreté", "misère", "besoin", "crise"],
  },
  {
    name: "Six de Denier",
    number: "6",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p06.jpg",
    fortune_telling: [
      "When you need help, ask for it",
      "Remember, though: what you receive may be limited by what you've given to others in the past",
    ],
    keywords: ["charité", "justice", "coopération", "partage"],
  },
  {
    name: "Sept de Denier",
    number: "7",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p07.jpg",
    fortune_telling: [
      "Things won't work out as expected",
      "Pick up the pieces and prepare to move on",
    ],
    keywords: ["estimation", "évaluation", "réévaluation", "réflexion"],
  },
  {
    name: "Huit de Denier",
    number: "8",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p08.jpg",
    fortune_telling: [
      "Stop over-analyzing, researching, and outlining",
      "Buckle down and get the work done",
    ],
    keywords: ["effort", "assiduité au travail", "compétence"],
  },
  {
    name: "Neuf de Denier",
    number: "9",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p09.jpg",
    fortune_telling: [
      "Until you appreciate what you have, you won't have any luck getting more",
    ],
    keywords: ["entraînement", "discipline", "confiance", "suffisant"],
  },
  {
    name: "Dix de Denier",
    number: "10",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p10.jpg",
    fortune_telling: [
      "Big money is in the near future",
      "Expect a powerful blessing to come your way",
    ],
    keywords: ["richesse", "abondance", "acquisition", "avidité"],
  },
  {
    name: "Valet de Denier",
    number: "11",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p11.jpg",
    fortune_telling: [
      "This card represents a young man or woman with an earthy, practical demeanor, likely born an Aries, Taurus, or Gemini, who playfully encourages you to take financial or sexual risks",
    ],
    keywords: [
      "praticité",
      "prosperité",
      "apprentissage",
      "croissance",
      "adolescence",
    ],
  },
  {
    name: "Chevalier de Denier",
    number: "12",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p12.jpg",
    fortune_telling: [
      "A stingy person may chide you for spending money",
      "Be prepared to defend an economic or sexual décision",
    ],
    keywords: ["caution", "focus", "realism", "invention"],
  },
  {
    name: "Reine de Denier",
    number: "13",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p13.jpg",
    fortune_telling: [
      "This card represents a woman with an expansive, sensual nature, likely born between December 13th and 31st, who uses sensual appeal and the promise of reward to sway others to her point of view",
    ],
    keywords: ["luxe", "comfort", "ingéniosité", "générosité", "prosperité"],
  },
  {
    name: "Roi de Denier",
    number: "14",
    arcana: "Minor Arcana",
    suit: "Deniers",
    img: "p14.jpg",
    fortune_telling: [
      "This card represents an older man with a financially, socially, and politically conservative spirit, likely born between August 12th and September 11th, who is known for putting his money where his mouth is",
    ],
    keywords: ["stabilité", "fiabilité", "confiance", "intervention"],
  },
];
